# Generated by Django 5.2 on 2025-05-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transactionitem_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="customer_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
