# Generated by Django 5.2 on 2025-05-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0003_transaction_customer_name_transaction_customer_phone_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="customer_name",
            field=models.CharField(max_length=50),
        ),
    ]
